In [2]:
import pandas as pd

dataset=pd.read_json('/home/hammadali08/Personal/FYP Datasets/News_Category_Dataset_v3.json',lines=True)
dataset=dataset.head(1000)
dataset

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
995,https://www.huffpost.com/entry/china-weighs-ex...,China Weighs Exit From 'Zero COVID' And The Ri...,WORLD NEWS,The change does not appear imminent as the gov...,"Dake Kang and Huizhong Wu, AP",2022-03-18
996,https://www.huffpost.com/entry/russian-missile...,Russian Missiles Hit Near Lviv Airport As Stri...,WORLD NEWS,World leaders have been calling for an investi...,"Cara Anna, AP",2022-03-18
997,https://www.huffpost.com/entry/assad-uae_n_623...,"Syria's Assad Visits UAE, 1st Trip To Arab Cou...",WORLD NEWS,Assad's office said he met with Sheikh Mohamed...,,2022-03-18
998,https://www.huffpost.com/entry/japan-earthquak...,"Strong Japan Earthquake Kills 4, Injures 107",WORLD NEWS,The 7.4-magnitude temblor knocked out power an...,"Mari Yamaguchi, AP",2022-03-17


In [3]:
dataset = dataset.rename(columns={'headline': 'English'})
dataset= dataset.rename(columns={'short_description': 'French'})
dataset

,link,English,category,French,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
995,https://www.huffpost.com/entry/china-weighs-ex...,China Weighs Exit From 'Zero COVID' And The Ri...,WORLD NEWS,The change does not appear imminent as the gov...,"Dake Kang and Huizhong Wu, AP",2022-03-18
996,https://www.huffpost.com/entry/russian-missile...,Russian Missiles Hit Near Lviv Airport As Stri...,WORLD NEWS,World leaders have been calling for an investi...,"Cara Anna, AP",2022-03-18
997,https://www.huffpost.com/entry/assad-uae_n_623...,"Syria's Assad Visits UAE, 1st Trip To Arab Cou...",WORLD NEWS,Assad's office said he met with Sheikh Mohamed...,,2022-03-18
998,https://www.huffpost.com/entry/japan-earthquak...,"Strong Japan Earthquake Kills 4, Injures 107",WORLD NEWS,The 7.4-magnitude temblor knocked out power an...,"Mari Yamaguchi, AP",2022-03-17


In [4]:
import re
corpus = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['English'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus.append(review)

In [5]:
corpus

['over 4 million americans roll up sleeves for omicron targeted covid boosters',
 'american airlines flyer charged banned for life after punching flight attendant on video',
 '23 of the funniest tweets about cats and dogs this week sept 17 23',
 'the funniest tweets from parents this week sept 17 23',
 'woman who called cops on black bird watcher loses lawsuit against ex employer',
 'cleaner was dead in belk bathroom for 4 days before body found police',
 'reporter gets adorable surprise from her boyfriend while live on tv',
 'puerto ricans desperate for water after hurricane fiona s rampage',
 'how a new documentary captures the complexity of being a child of immigrants',
 'biden at un to call russian war an affront to body s charter',
 'world cup captains want to wear rainbow armbands in qatar',
 'man sets himself on fire in apparent protest of funeral for japan s abe',
 'fiona threatens to become category 4 storm headed to bermuda',
 'twitch bans gambling sites after streamer scams 

In [6]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))   # Simple Preprcoess make it lowe r case
words

[['over',
  'million',
  'americans',
  'roll',
  'up',
  'sleeves',
  'for',
  'omicron',
  'targeted',
  'covid',
  'boosters'],
 ['american',
  'airlines',
  'flyer',
  'charged',
  'banned',
  'for',
  'life',
  'after',
  'punching',
  'flight',
  'attendant',
  'on',
  'video'],
 ['of',
  'the',
  'funniest',
  'tweets',
  'about',
  'cats',
  'and',
  'dogs',
  'this',
  'week',
  'sept'],
 ['the', 'funniest', 'tweets', 'from', 'parents', 'this', 'week', 'sept'],
 ['woman',
  'who',
  'called',
  'cops',
  'on',
  'black',
  'bird',
  'watcher',
  'loses',
  'lawsuit',
  'against',
  'ex',
  'employer'],
 ['cleaner',
  'was',
  'dead',
  'in',
  'belk',
  'bathroom',
  'for',
  'days',
  'before',
  'body',
  'found',
  'police'],
 ['reporter',
  'gets',
  'adorable',
  'surprise',
  'from',
  'her',
  'boyfriend',
  'while',
  'live',
  'on',
  'tv'],
 ['puerto',
  'ricans',
  'desperate',
  'for',
  'water',
  'after',
  'hurricane',
  'fiona',
  'rampage'],
 ['how',
  'new',


In [7]:
all_words = [word for sentence in words for word in sentence]

# Get unique words
unique_words_input = set(all_words)

# Count them
print("Number of unique words:", len(unique_words_input))
print("Unique words:", unique_words_input)

Number of unique words: 3994
Unique words: {'degrassi', 'grant', 'ever', 'displaced', 'pitchforks', 'experts', 'searches', 'having', 'fact', 'ruling', 'affleck', 'watergate', 'royal', 'wagner', 'manchin', 'deadline', 'richie', 'dunst', 'champion', 'continue', 'fisherman', 'far', 'jello', 'failure', 'tackles', 'nightmare', 'pugh', 'spain', 'ezra', 'kevin', 'coli', 'queens', 'hailed', 'merriam', 'heart', 'video', 'pregnant', 'ocasio', 'bouts', 'real', 'fein', 'louisville', 'climbing', 'month', 'kills', 'walk', 'field', 'blond', 'vaccines', 'ranking', 'emme', 'beauty', 'indicted', 'himself', 'being', 'purchase', 'knew', 'former', 'are', 'persuasion', 'send', 'taking', 'authorizes', 'ton', 'mass', 'marilyn', 'heard', 'talking', 'steal', 'meg', 'alabama', 'disruption', 'coronavirus', 'seems', 'those', 'retires', 'conflict', 'proposals', 'kids', 'depends', 'salary', 'between', 'clarence', 'eat', 'mysterious', 'spread', 'add', 'spotted', 'cup', 'takes', 'security', 'founder', 'jong', 'bieber'

In [8]:
max_len_input = max(len(sentence) for sentence in words)
longest_sentence = max(words, key=len)

print("Max number of words:", max_len_input)
print("Sentence with max words:", longest_sentence)

Max number of words: 17
Sentence with max words: ['alex', 'jones', 'sandy', 'hook', 'defamation', 'trial', 'is', 'set', 'to', 'begin', 'here', 'how', 'it', 'got', 'to', 'this', 'point']


## Input Encoding:

In [9]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
one_hot_input=[one_hot(word, len(unique_words_input)) for word in corpus]
one_hot_input

[[913, 3614, 1523, 2206, 1374, 3765, 428, 2533, 2235, 3737, 2873, 3682],
 [1228, 1553, 1284, 2581, 318, 2533, 1411, 2025, 1990, 92, 3222, 902, 730],
 [3586,
  827,
  3504,
  3593,
  2550,
  2585,
  1666,
  1081,
  343,
  2435,
  233,
  2942,
  1197,
  3586],
 [3504, 3593, 2550, 2931, 205, 2435, 233, 2942, 1197, 3586],
 [3715, 2945, 730, 1454, 902, 149, 598, 470, 3270, 731, 2604, 1817, 3056],
 [11, 2351, 1886, 498, 1135, 1283, 2533, 3614, 1818, 1339, 977, 2239, 1159],
 [2557, 2160, 3225, 3854, 2931, 93, 219, 917, 3358, 902, 364],
 [3989, 483, 96, 2533, 2544, 2025, 2578, 727, 277, 644],
 [788, 2945, 3935, 2515, 3876, 3504, 1513, 827, 686, 2945, 3876, 827, 2360],
 [897, 3906, 1512, 3936, 1776, 1354, 502, 3029, 2140, 3936, 977, 277, 1909],
 [1819, 3497, 1365, 3527, 3936, 3145, 2204, 2788, 498, 3458],
 [3947,
  2379,
  3063,
  902,
  1703,
  498,
  2264,
  2877,
  827,
  3558,
  2533,
  2560,
  277,
  2989],
 [727, 3667, 3936, 829, 1611, 3614, 1435, 540, 3936, 1584],
 [3598, 3910, 1777, 395

In [11]:
input_padding=pad_sequences(one_hot_input, maxlen=max_len_input, padding='post')
input_padding

array([[ 913, 3614, 1523, ...,    0,    0,    0],
       [1228, 1553, 1284, ...,    0,    0,    0],
       [3586,  827, 3504, ...,    0,    0,    0],
       ...,
       [2682,  277, 1939, ...,    0,    0,    0],
       [1478, 2560, 3443, ...,    0,    0,    0],
       [2780, 1886, 2407, ...,    0,    0,    0]], dtype=int32)

In [12]:

from keras.layers import Embedding, LSTM, Input

encoder_inputs = Input(shape=(None,))
embedding_layer = Embedding(input_dim=len(unique_words_input), output_dim=256)
encoder_embeddings = embedding_layer(encoder_inputs)
encoder_outputs, state_h, state_c = LSTM(256, return_state=True)(encoder_embeddings)

2025-09-02 11:50:52.532236: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


# Output Preprocessing

In [13]:
corpus1 = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['French'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus1.append(review)

In [14]:
decoder_input_data = ["<start> " + txt + "" for txt in corpus1]
decoder_target_data= ["" + txt + " <end>" for txt in corpus1]
decoder_input_data

['<start> health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the u s ordered for the fall',
 '<start> he was subdued by passengers and crew when he fled to the back of the aircraft after the confrontation according to the u s attorney s office in los angeles',
 '<start> until you have a dog you don t understand what could be eaten',
 '<start> accidentally put grown up toothpaste on my toddler s toothbrush and he screamed like i was cleaning his teeth with a carolina reaper dipped in tabasco sauce',
 '<start> amy cooper accused investment firm franklin templeton of unfairly firing her and branding her a racist after video of the central park encounter went viral',
 '<start> the 63 year old woman was seen working at the south carolina store on thursday she was found dead monday after her family reported her missing authorities said',
 '<start> who s that behind you an anchor for new york s pix11 asked journalist mic

In [15]:
words1=[]
for sent in corpus1:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words1.append(simple_preprocess(sent))
words1

[['health',
  'experts',
  'said',
  'it',
  'is',
  'too',
  'early',
  'to',
  'predict',
  'whether',
  'demand',
  'would',
  'match',
  'up',
  'with',
  'the',
  'million',
  'doses',
  'of',
  'the',
  'new',
  'boosters',
  'the',
  'ordered',
  'for',
  'the',
  'fall'],
 ['he',
  'was',
  'subdued',
  'by',
  'passengers',
  'and',
  'crew',
  'when',
  'he',
  'fled',
  'to',
  'the',
  'back',
  'of',
  'the',
  'aircraft',
  'after',
  'the',
  'confrontation',
  'according',
  'to',
  'the',
  'attorney',
  'office',
  'in',
  'los',
  'angeles'],
 ['until',
  'you',
  'have',
  'dog',
  'you',
  'don',
  'understand',
  'what',
  'could',
  'be',
  'eaten'],
 ['accidentally',
  'put',
  'grown',
  'up',
  'toothpaste',
  'on',
  'my',
  'toddler',
  'toothbrush',
  'and',
  'he',
  'screamed',
  'like',
  'was',
  'cleaning',
  'his',
  'teeth',
  'with',
  'carolina',
  'reaper',
  'dipped',
  'in',
  'tabasco',
  'sauce'],
 ['amy',
  'cooper',
  'accused',
  'investmen

In [16]:
max_len_output = max(len(sentence) for sentence in words1)
longest_sentence = max(words1, key=len)

print("Max number of words:", max_len_output)
print("Sentence with max words:", longest_sentence)

Max number of words: 41
Sentence with max words: ['when', 'elsa', 'avila', 'looks', 'at', 'the', 'scar', 'that', 'runs', 'down', 'her', 'torso', 'she', 'can', 'help', 'remember', 'may', 'when', 'gunman', 'stormed', 'her', 'fourth', 'grade', 'wing', 'at', 'robb', 'elementary', 'in', 'uvalde', 'texas', 'killing', 'children', 'and', 'two', 'teachers', 'and', 'leaving', 'her', 'and', 'others', 'wounded']


In [17]:
all_words1 = [word for sentence in words1 for word in sentence]

# Get unique words
unique_words_output = set(all_words1)

# Count them
print("Number of unique words:", len(unique_words_output))
print("Unique words:", unique_words_output)

Number of unique words: 5239
Unique words: {'ever', 'stirred', 'affleck', 'far', 'realized', 'panicking', 'joy', 'fein', 'withdrawal', 'guterres', 'duties', 'supplies', 'knew', 'former', 'actions', 'mass', 'youtube', 'marsupials', 'trick', 'kyle', 'sought', 'marc', 'add', 'cup', 'brnovich', 'cuellar', 'lady', 'must', 'korea', 'pence', 'latest', 'unaware', 'dolls', 'raphael', 'malaysia', 'dense', 'clueless', 'points', 'florida', 'bbc', 'vital', 'blow', 'dressed', 'eyeliner', 'jaws', 'obsession', 'pot', 'struggled', 'upcoming', 'life', 'duchess', 'stylized', 'muckrakers', 'mean', 'unfolded', 'more', 'witness', 'trading', 'then', 'tell', 'hog', 'tan', 'part', 'owned', 'aides', 'fight', 'exactly', 'luck', 'waves', 'proxy', 'shouldn', 'beach', 'despised', 'union', 'directed', 'intervened', 'judges', 'his', 'earlier', 'cops', 'occurred', 'overturn', 'benchmark', 'carolyn', 'eldest', 'suspects', 'kitty', 'interfere', 'cooking', 'battlefield', 'lockdown', 'reds', 'another', 'birch', 'instagram

In [18]:
decoder_input=[one_hot(word, len(unique_words_output)) for word in decoder_input_data]
decoder_input

[[2289,
  1940,
  650,
  2254,
  2333,
  5142,
  2497,
  3472,
  477,
  1118,
  2578,
  3353,
  3761,
  78,
  255,
  976,
  1749,
  494,
  239,
  4240,
  4565,
  1749,
  1673,
  2296,
  1749,
  2164,
  3943,
  1568,
  4279,
  1749,
  2436],
 [2289,
  3160,
  1778,
  3664,
  4297,
  2033,
  4837,
  4926,
  1382,
  3160,
  1237,
  477,
  1749,
  1736,
  4565,
  1749,
  4228,
  3978,
  1749,
  466,
  324,
  477,
  1749,
  2164,
  3943,
  2734,
  3943,
  1076,
  4146,
  3291,
  3489],
 [2289,
  1280,
  1038,
  5063,
  2348,
  3749,
  1038,
  3655,
  36,
  5218,
  157,
  3803,
  5,
  2009],
 [2289,
  1067,
  2631,
  3403,
  255,
  297,
  1223,
  4771,
  3757,
  3943,
  4712,
  4837,
  3160,
  4127,
  2552,
  2971,
  1778,
  2690,
  602,
  4084,
  976,
  2348,
  1649,
  5046,
  2808,
  4146,
  513,
  1599],
 [2289,
  375,
  2632,
  1650,
  1759,
  673,
  1859,
  425,
  4565,
  2496,
  2933,
  4026,
  4837,
  3581,
  4026,
  2348,
  2371,
  3978,
  2503,
  4565,
  1749,
  179,
  1891,
  2803,

In [19]:
decoder_target=[one_hot(word, len(unique_words_output)) for word in decoder_target_data]
decoder_target

[[1940,
  650,
  2254,
  2333,
  5142,
  2497,
  3472,
  477,
  1118,
  2578,
  3353,
  3761,
  78,
  255,
  976,
  1749,
  494,
  239,
  4240,
  4565,
  1749,
  1673,
  2296,
  1749,
  2164,
  3943,
  1568,
  4279,
  1749,
  2436,
  2628],
 [3160,
  1778,
  3664,
  4297,
  2033,
  4837,
  4926,
  1382,
  3160,
  1237,
  477,
  1749,
  1736,
  4565,
  1749,
  4228,
  3978,
  1749,
  466,
  324,
  477,
  1749,
  2164,
  3943,
  2734,
  3943,
  1076,
  4146,
  3291,
  3489,
  2628],
 [1280,
  1038,
  5063,
  2348,
  3749,
  1038,
  3655,
  36,
  5218,
  157,
  3803,
  5,
  2009,
  2628],
 [1067,
  2631,
  3403,
  255,
  297,
  1223,
  4771,
  3757,
  3943,
  4712,
  4837,
  3160,
  4127,
  2552,
  2971,
  1778,
  2690,
  602,
  4084,
  976,
  2348,
  1649,
  5046,
  2808,
  4146,
  513,
  1599,
  2628],
 [375,
  2632,
  1650,
  1759,
  673,
  1859,
  425,
  4565,
  2496,
  2933,
  4026,
  4837,
  3581,
  4026,
  2348,
  2371,
  3978,
  2503,
  4565,
  1749,
  179,
  1891,
  2803,
  3795,

In [20]:
decoder_input_data=pad_sequences(decoder_input, maxlen=max_len_output, padding='post')
decoder_input_data.shape

(1000, 41)

In [21]:
decoder_target_data=pad_sequences(decoder_target, maxlen=max_len_output, padding='post')
decoder_target_data.shape

(1000, 41)

In [22]:
from tensorflow.keras.utils import to_categorical

decoder_target_data = to_categorical(
    decoder_target_data,
    num_classes=len(unique_words_output)     # same as your output layer vocab size
)
decoder_target_data.shape

(1000, 41, 5239)

In [23]:
import tensorflow as tf
embedding_dim = 16

encoder_embedding = tf.keras.layers.Embedding(input_dim=len(unique_words_input), output_dim=embedding_dim)
decoder_embedding = tf.keras.layers.Embedding(input_dim=len(unique_words_output), output_dim=embedding_dim)

# Get embeddings
enc_inp = encoder_embedding(input_padding)  # shape: (batch, seq_len, 16)
dec_inp = decoder_embedding(decoder_input_data)
print("enc_inp shape:", enc_inp.shape)
print("dec_inp shape:", dec_inp.shape)

enc_inp shape: (1000, 17, 16)
dec_inp shape: (1000, 41, 16)


In [24]:
import tensorflow as tf
from jax.experimental.pallas.ops.gpu.attention_mgpu import attention
from tensorflow.python.ops import array_ops


class Attention:
	"""
	Attention class to implement attntion mentioned in papers:
		https://arxiv.org/abs/1506.03134
		https://arxiv.org/abs/1704.04368
		https://arxiv.org/abs/1508.04025
	"""

	def __init__(self, activation=None, is_decoder_present=False):
		self.activation = activation
		self.is_decoder_present = is_decoder_present

	def attention(
			self,
			encoder_states,
			enc_inp=None,
			decoder_states=None,
			time_major=False,
			return_score=False,
			return_context=False,
			return_alphas=False
			):
		"""
		score(t) = h(s).W.trans(h(t))  dim:[B, T2, T1] = [B, T1, D1].[D1, D2].transpose([B, T2, D2])
		alphas = softmax(t)
		Args:
			:param encoder_states: Encoder outputs on which attention is to be applied, shape: [B, T1, D1]
			:param enc_inp: Encoder inputs, shape: [B, T1, Dim]
			:param decoder_states: Decoder states, shape: [B, T2, D2]
				if None: self attention is implemented with dec_states tf.ones([B, 1, 1])
			:param activation: activation function to apply on score
			:param time_major: Default is False
				True if shape of encoder/decoder is (T, B, D)
				Flase if shape of encoder is (B, T, D)
			:param return_score: Default is False
			:param return_context: Defaults to False
		Returns:
			:return:
				returns outputs([B, T2, D1]) and
				if return_score is True: scores ([B, T2, T1])
				if return_context is True: context ([B, D1])
		"""
		if isinstance(encoder_states, tuple):
			# In case of Bi-RNN, concatenate the forward and the backward RNN outputs.
			encoder_states = tf.concat(encoder_states, 2)

		if time_major:
			# (T,B,D) => (B,T,D)
			encoder_states = tf.transpose(encoder_states, [1, 0, 2])
			decoder_states = tf.transpose(decoder_states, [1, 0, 2])

		batch_size = array_ops.shape(encoder_states)[0]

		if not self.is_decoder_present:
			decoder_states = tf.ones([batch_size, 1, 1], dtype=encoder_states.dtype, name="dec_states")

		encoder_n = encoder_states.shape[2].value  # D1 value - hidden size of the RNN layer encoder
		decoder_n = decoder_states.shape[2].value  # D2 value - hidden size of the RNN layer decoder

		# Trainable parameters
		with tf.variable_scope("attn/attn_weight"):
			w_omega = tf.get_variable(
				name="w_omega", shape=[encoder_n, decoder_n], initializer=tf.random_normal_initializer())  # [D1, D2]

		with tf.variable_scope("attn/score"):
			enc_reshape = tf.reshape(encoder_states, [-1, encoder_n], name="enc_reshape")  # [(B*T1), D1]
			h1 = tf.matmul(enc_reshape, w_omega)  # [(B*T1), D1][D1, D2] = [(B*T1), D2]
			h1_reshape = tf.reshape(h1, tf.stack([batch_size, -1, decoder_n]), name="h1_reshape")  # [B, T1, D2]
			dec_transpose = tf.transpose(decoder_states, [0, 2, 1])  # [B, D2, T2]
			if not self.activation:
				score = tf.matmul(h1_reshape, dec_transpose)  # [B, T1, D2][B, D2, T2] = [B, T1, T2]
			else:
				score = self.activation(tf.matmul(h1_reshape, dec_transpose))  # [B, T1, D2][B, D2, T2] = [B, T1, T2]
			score_transpose = tf.transpose(score, [0, 2, 1])  # [B, T2, T1]

		with tf.variable_scope("attn/align"):
			alphas = tf.nn.softmax(score_transpose, axis=2, name='alphas')  # [B, T2, T1] with softmax on T1

		with tf.variable_scope("attn/outputs"):
			alphas_argmax = tf.argmax(alphas, axis=2, name="outputs_argmax", output_type=tf.int32)  # [B, T2]
			outputs = tf.gather_nd(params=enc_inp, indices=self._index_matrix_to_pairs(alphas_argmax))

		# Output of (Bi-)RNN is reduced with attention vector; the result has (B,D1) shape
		with tf.variable_scope("attn/context_vec"):
			context = tf.reduce_sum(tf.matmul(alphas, encoder_states), axis=1, name="context")   # [B, D1]
		ret = [outputs]
		if return_score:
			ret.append(score_transpose)
		if return_context:
			ret.append(context)
		if return_alphas:
			ret.append(alphas)
		return tuple(ret)

	def _index_matrix_to_pairs(self, index_matrix):
		""" Method to create index to pairs in the first dimension
		[[3,1,2], [2,3,1]] -> [[[0, 3], [1, 1], [2, 2]],
								[[0, 2], [1, 3], [2, 1]]]
		Args:
		:param index_matrix: a Tensor of indexes
		Returns:
		:return Tensor representing the pairwise indexed index_matrix
		"""
		with tf.variable_scope("index_matrix_to_pairs"):
			replicated_first_indices = tf.range(tf.shape(index_matrix)[0])
			rank = len(index_matrix.get_shape())
			if rank == 2:
				replicated_first_indices = tf.tile(
					tf.expand_dims(replicated_first_indices, dim=1),
					[1, tf.shape(index_matrix)[1]])
			return tf.stack([replicated_first_indices, index_matrix], axis=rank)

In [25]:
from tensorflow.keras.layers import Embedding

encoder_embedding = Embedding(input_dim=len(unique_words_input), output_dim=50, mask_zero=True)
decoder_embedding = Embedding(input_dim=len(unique_words_output), output_dim=50, mask_zero=True)

encoder_input_emb = encoder_embedding(input_padding)  # [batch, max_input_len, embedding_dim]
decoder_input_emb = decoder_embedding(decoder_input_data)  # [batch, max_output_len, embedding_dim]

In [43]:
from tensorflow.keras.layers import Dense, Bidirectional
from tensorflow.keras.models import Sequential

dimensions=60
model=Sequential()
model.add(Embedding(len(unique_words_input),dimensions))
model.add(Bidirectional(LSTM(314)))
model.add(Dense(40,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

ValueError: Unrecognized data type: x=[[ 913 3614 1523 ...    0    0    0]
 [1228 1553 1284 ...    0    0    0]
 [3586  827 3504 ...    0    0    0]
 ...
 [2682  277 1939 ...    0    0    0]
 [1478 2560 3443 ...    0    0    0]
 [2780 1886 2407 ...    0    0    0]] (of type <class 'numpy.ndarray'>)

In [48]:
attention_layer = Attention(is_decoder_present=True)

outputs, scores, context, alphas = attention_layer.attention(
    encoder_states=encoder_outputs_,   # BiLSTM hidden states
    enc_inp=enc_inp,                  # encoder embeddings (for gather_nd)
    decoder_states=dec_inp,   # decoder hidden states
    return_score=True,
    return_context=True,
    return_alphas=True
)

IndexError: tuple index out of range

In [3]:
from attention import Attention  # or wherever your class is

attn = Attention()

In [23]:
# ===== Encoder =====
encoder_inputs = Input(shape=(None,))   # input is a sequence of word indices
x = Embedding(input_dim=len(unique_words_input), output_dim=127, input_length=max_len_input)(encoder_inputs)

# LSTM encoder
encoder_lstm = LSTM(256, return_state=True)  # return_state gives hidden + cell states
encoder_outputs, state_h, state_c = encoder_lstm(x)

# Encoder states (to pass into decoder)
encoder_states = [state_h, state_c]


/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
# ===== Decoder =====
decoder_inputs = Input(shape=(None,))  # target sequence input
decoder_embedding = Embedding(input_dim=len(unique_words_output), output_dim=127, input_length=max_len_output)(decoder_inputs)

# LSTM decoder, initialized with encoder states
decoder_lstm = LSTM(256, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)


In [25]:
# Final dense layer to predict word probabilities
from tensorflow.keras.layers import Dense
decoder_dense = Dense(len(unique_words_output), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [26]:
from tensorflow.keras.models import Model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [ ]:
model.fit([input_padding, decoder_input_data], decoder_target_data,
          batch_size=664,
          epochs=2,
          validation_split=0.2)

