In [3]:
import pandas as pd
dataset=pd.read_csv('/home/hammadali08/Personal/CSV file/FakeNewsNet.csv')
dataset

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1
...,...,...,...,...,...
23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52,1
23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7,0
23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26,1
23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24,0


In [156]:
dataset['real'].value_counts()

real
1    17441
0     5755
Name: count, dtype: int64

In [12]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
stopwords = set([w.lower() for w in stopwords.words('english')])
corpus=[]
for i in range(0,len(dataset)):
    review=re.sub('^[A-Za-z]',' ', dataset['title'][i])
    review=review.lower()
    review=review.split()

    review=[lemmatizer.lemmatize(words) for words in review if words not in stopwords]
    review=' '.join(review)
    corpus.append(review)

In [13]:
corpus

["andi burruss explodes rape accusation 'real housewife atlanta' reunion (video)",
 "eople's choice award 2018: best red carpet look",
 "ophia bush sends sweet birthday message 'one tree hill' co-star hilarie burton: 'breyton 4eva'",
 'olombian singer maluma spark rumour inappropriate relationship aunt',
 'ossip girl 10 year later: upper east siders shocked world changed pop culture forever',
 'wen stefani got dumped blake shelton "jealousy drama" (exclusive)',
 'roward county sheriff fired lying parkland',
 "mber rose shuts french montana dating rumors, call rapper 'bruvaaa'",
 "indy kaling make first post-baby appearance disneyland 'wrinkle time' co-star",
 'atharine mcphee butcher tony nominations: “i drinking”',
 '‘wags miami’ star ashley nicole robert philip wheeler married',
 'el gibson: hollywood pedophile nowhere left hide',
 'edium tyler henry address ‘chilling’ message kristin cavallari’s deceased brother expressed reading',
 'wts season 27 results: week 5 - disney night',
 '

In [15]:
len(corpus)

23196

In [16]:
dataset['real'].shape

(23196,)

In [17]:
from tensorflow.keras.preprocessing.text import one_hot

2025-08-25 22:15:34.424638: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-25 22:15:34.429945: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-25 22:15:34.442964: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1756142134.467484   52868 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756142134.475020   52868 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1756142134.493719   52868 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

In [128]:
vocab_size=4000
onehot_=[one_hot(words,vocab_size) for words in corpus]
onehot_

[[77, 2708, 860, 2463, 307, 1303, 671, 1468, 887, 465],
 [1702, 1348, 3507, 3293, 1703, 1931, 2809, 881],
 [918,
  3332,
  1610,
  683,
  3757,
  520,
  78,
  2813,
  718,
  853,
  1465,
  3059,
  936,
  2545,
  3463],
 [2516, 2695, 3838, 1042, 1054, 2445, 3496, 2238],
 [2713,
  3690,
  913,
  2740,
  1304,
  121,
  213,
  1807,
  2981,
  1336,
  3428,
  715,
  1699,
  3643],
 [2128, 1031, 1976, 2941, 3872, 3515, 1126, 3812, 3952],
 [1014, 211, 1860, 395, 3033, 1806],
 [791, 3715, 1645, 3100, 3733, 1266, 238, 3186, 3001, 2039],
 [2724, 3537, 2850, 521, 1400, 235, 2501, 3067, 317, 3602, 853, 1465],
 [1711, 946, 1541, 2654, 2937, 3693, 3524],
 [718, 3237, 1465, 3692, 1, 339, 858, 2040, 3299],
 [3353, 3921, 3679, 3035, 2290, 524, 378],
 [1524, 3765, 3575, 2640, 2074, 520, 2128, 1081, 1474, 3225, 2390, 272],
 [2120, 3670, 3882, 1186, 2198, 3666, 3537, 3634],
 [3002, 3992, 1328, 1108, 531, 2990],
 [3666, 1785, 2182, 3353, 3972, 2624, 401, 3995, 2084],
 [546, 1116, 3986, 1944, 2496, 3930, 28

In [129]:
len(onehot_)

23196

In [130]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [131]:
sent_length=20
padding=pad_sequences(onehot_,maxlen=sent_length,padding='post')
padding

array([[  77, 2708,  860, ...,    0,    0,    0],
       [1702, 1348, 3507, ...,    0,    0,    0],
       [ 918, 3332, 1610, ...,    0,    0,    0],
       ...,
       [1263, 3106, 3155, ...,    0,    0,    0],
       [3690, 1248, 1409, ...,    0,    0,    0],
       [1446, 3482, 2896, ...,    0,    0,    0]], dtype=int32)

In [132]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM,Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [161]:
dim=50
model=Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=dim,input_length=sent_length))
model.add(Dropout(0.2))
model.add(LSTM(400))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


## Training Model:

In [162]:
X=padding
Y=dataset['real']

In [163]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [164]:
model.fit(x_train,y_train,epochs=4,batch_size=10,validation_data=(x_test,y_test))

Epoch 1/4
1856/1856 ━━━━━━━━━━━━━━━━━━━━ 84s 45ms/step - accuracy: 0.7924 - loss: 0.4782 - val_accuracy: 0.8218 - val_loss: 0.4217
Epoch 2/4
1856/1856 ━━━━━━━━━━━━━━━━━━━━ 79s 42ms/step - accuracy: 0.8384 - loss: 0.3793 - val_accuracy: 0.8265 - val_loss: 0.4041
Epoch 3/4
1856/1856 ━━━━━━━━━━━━━━━━━━━━ 77s 42ms/step - accuracy: 0.8582 - loss: 0.3330 - val_accuracy: 0.8181 - val_loss: 0.4149
Epoch 4/4
1856/1856 ━━━━━━━━━━━━━━━━━━━━ 86s 47ms/step - accuracy: 0.8738 - loss: 0.2937 - val_accuracy: 0.8231 - val_loss: 0.4539


In [165]:
import numpy as np
y_pred=model.predict(x_test)
y_pred=np.where(y_pred>0.5,1,0) # AUC ROC Curve

145/145 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step


In [166]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 554,  538],
       [ 283, 3265]])

In [167]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8230603448275862

# Prediction of new Sentences

In [183]:
news=input('Enter News: ')
news

'MY name is Abaro'

In [184]:
news=news.lower()
news_embeded=one_hot(news,vocab_size)
news_embeded

[2831, 3138, 1783, 2848]

In [185]:
news_padding=pad_sequences([news_embeded],maxlen=sent_length,padding='post')
news_padding

array([[2831, 3138, 1783, 2848,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [186]:
news_padding

array([[2831, 3138, 1783, 2848,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [187]:
pred=model.predict(news_padding)
if pred>0.5:
    print("Right News")
else:
    print("Fake News")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Right News
