# RNN(Recurent Neural Network)
Used for Text and Time Series data
### Types:
1. One to One RNN (eg. Image Classification)
2. One to Many RNN (eg. Text Generation)
3. Many to One RNN (eg. Sentiment Analysis)
4. Many to Many RNN (eg. Language Translation, Chatbots)

# LSTM RNN
1. This is basically better than RNN in large sentences.
2. It have the ability to Forget information ang get information.

## What are things we have to do in Deep Learning Embedding Layer:
1. Sentences
2. Convert into OHE (With Vocabulary(Unique words) size given)
3. Padding ( Post Padding, Pre Padding)
4. OHE ==> Vectors

In [1]:
from tensorflow.keras.preprocessing.text import one_hot
#One_Hot is for One Hot Encoding

2025-08-24 17:21:26.497353: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-24 17:21:26.692496: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-24 17:21:26.751179: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1756038086.859765    5638 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756038086.879688    5638 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1756038087.050563    5638 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary Size: The number of Dimensions
vocab_size = 1000
vocab_size

1000

My sentence will be trained on these 1000 Vocabolary Size.
### Larger Vocabulary Size means better feature Representaion.

 ## ONE HOT Representation

In [5]:
one_hot_rep=[one_hot(words,vocab_size) for words in sent]
one_hot_rep

[[712, 938, 411, 681],
 [712, 938, 411, 88],
 [712, 680, 411, 6],
 [157, 192, 157, 896, 720],
 [157, 192, 157, 896, 911],
 [826, 712, 592, 411, 329],
 [936, 643, 151, 896]]

At these certain places in my Vocabulary size is ONE which represent my those words in senteneces

# Padding:
### Sentences are of different lengths, Padding makes sure to make them of equal Vectors Length by adding Zeros.

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=7           # Every Sentence Vector will become of the length 7
embedded_sent=pad_sequences(one_hot_rep,maxlen=sent_length,padding='pre') # Post means Zeros will added at the end and Pre means zeros will added at first.
embedded_sent

array([[  0,   0,   0, 712, 938, 411, 681],
       [  0,   0,   0, 712, 938, 411,  88],
       [  0,   0,   0, 712, 680, 411,   6],
       [  0,   0, 157, 192, 157, 896, 720],
       [  0,   0, 157, 192, 157, 896, 911],
       [  0,   0, 826, 712, 592, 411, 329],
       [  0,   0,   0, 936, 643, 151, 896]], dtype=int32)

In [8]:
# In How many dimensions our FEATURES should be Represented
dim=12

In [9]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-08-24 17:21:32.409179: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 7, 10)             │        10,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (7, 7, 10, 20)         │        20,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 30,000 (117.19 KB)

 Trainable params: 30,000 (117.19 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_sent)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step


array([[[ 0.01295442,  0.04300677,  0.03601008,  0.0379365 ,
         -0.04466688, -0.03158217, -0.02803916,  0.00621621,
          0.02597568, -0.03505914],
        [ 0.01295442,  0.04300677,  0.03601008,  0.0379365 ,
         -0.04466688, -0.03158217, -0.02803916,  0.00621621,
          0.02597568, -0.03505914],
        [ 0.01295442,  0.04300677,  0.03601008,  0.0379365 ,
         -0.04466688, -0.03158217, -0.02803916,  0.00621621,
          0.02597568, -0.03505914],
        [ 0.02082982, -0.00932018, -0.02976068, -0.01768869,
          0.009092  ,  0.03232118,  0.02472533,  0.02881325,
         -0.02097235, -0.04006533],
        [-0.01457143, -0.02242253, -0.04283719,  0.01585679,
         -0.03864545, -0.03255714,  0.03697381,  0.00928337,
         -0.02685933, -0.01552434],
        [-0.0489624 ,  0.0039857 ,  0.00670651, -0.04674453,
         -0.00488107,  0.04693801,  0.01465377, -0.04098326,
         -0.00529488,  0.03140369],
        [ 0.03522542,  0.0378933 , -0.02684969,  0.0

## Another sent Example:

In [12]:
sent1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [13]:
voabulary_size=1000

In [14]:
ohe=[one_hot(words,voabulary_size) for words in sent1]
ohe

[[712, 290, 179, 157, 309, 857],
 [283, 292, 179, 189, 313, 983],
 [157, 714, 857, 458],
 [712, 551, 179, 828, 712, 658],
 [481, 294, 70, 179, 189, 313, 983],
 [415, 179, 189, 313, 882, 905]]

In [15]:
sent_length2=9

In [16]:
padded_sent=pad_sequences(ohe,maxlen=sent_length2,padding='pre')
padded_sent

array([[  0,   0,   0, 712, 290, 179, 157, 309, 857],
       [  0,   0,   0, 283, 292, 179, 189, 313, 983],
       [  0,   0,   0,   0,   0, 157, 714, 857, 458],
       [  0,   0,   0, 712, 551, 179, 828, 712, 658],
       [  0,   0, 481, 294,  70, 179, 189, 313, 983],
       [  0,   0,   0, 415, 179, 189, 313, 882, 905]], dtype=int32)

In [24]:
dim=20

In [25]:
model1=Sequential()
model1.add(Embedding(voabulary_size,20))
model1.compile(optimizer='adam',loss='mse')

In [27]:
model1.predict(padded_sent)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step


array([[[ 0.03680391, -0.04686502,  0.02514223, ...,  0.03491284,
          0.01868716,  0.04692116],
        [ 0.03680391, -0.04686502,  0.02514223, ...,  0.03491284,
          0.01868716,  0.04692116],
        [ 0.03680391, -0.04686502,  0.02514223, ...,  0.03491284,
          0.01868716,  0.04692116],
        ...,
        [-0.00194119, -0.00156941, -0.01341649, ..., -0.03846148,
          0.04124815, -0.01113208],
        [-0.02303274, -0.01794094,  0.01170973, ...,  0.0152464 ,
          0.03247228,  0.00797312],
        [ 0.02910839, -0.04792425,  0.04099854, ..., -0.01161698,
          0.02850742, -0.03760239]],

       [[ 0.03680391, -0.04686502,  0.02514223, ...,  0.03491284,
          0.01868716,  0.04692116],
        [ 0.03680391, -0.04686502,  0.02514223, ...,  0.03491284,
          0.01868716,  0.04692116],
        [ 0.03680391, -0.04686502,  0.02514223, ...,  0.03491284,
          0.01868716,  0.04692116],
        ...,
        [-0.02073141, -0.03061429,  0.01268495, ..., -

In [30]:
model1.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (6, 9, 20)             │        20,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 20,000 (78.12 KB)

 Trainable params: 20,000 (78.12 KB)

 Non-trainable params: 0 (0.00 B)