In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st
from nacl.bindings import crypto_pwhash_ALG_ARGON2I13

In [2]:
first_data=pd.read_csv("/home/hammadali08/Videos/Moviesdata.csv")

                                Hypothesis T test(uses when number of data is less than 30)

In [3]:
pop_mean=150
n_data=25
sample_mean=148
sample_std=5
alpha=0.05

In [4]:
t_table=(st.t.ppf(alpha,n_data-1))

In [5]:
T_test=(sample_mean-pop_mean)/(sample_std/np.sqrt(n_data))

In [6]:
if t_table<T_test:
    print("Ho is Right")
else:
    print("Ha is right")

Ha is right


                                    Another Example of T test

In [7]:
first_mean=80
second_mean=75
first_std=5
second_std=6
n=20

 Ho will believe both are equal

Ha will believe there is a difference in it

In [32]:
T_cal=(first_mean-second_mean)/(np.sqrt((first_std**2/n)+(second_std**2/n)))
T_cal

np.float64(2.862991671569341)

In [9]:
alpha=0.025

In [10]:
T_value=st.t.ppf(1-alpha,38)

In [11]:
if T_value<T_cal:
    print("Ha is right")
else:
    print("Ho is right")

Ha is right


                                    Trying it on another Example

In [12]:
data1 = np.array([52.48, 49.31, 53.24, 57.62, 48.83, 48.83, 57.90, 53.84, 47.65, 52.71,
         47.66, 47.66, 58.52, 53.00, 40.28, 54.58, 50.44, 41.45, 51.46, 45.69,
         45.88, 54.17, 49.96, 49.53, 55.66, 44.95, 50.46, 53.92, 49.29, 53.28,
         52.92, 48.31, 45.84, 45.21, 49.96])

data2 = np.array([45.90, 53.04, 42.20, 45.36, 52.98, 55.69, 52.86, 51.42, 50.49, 44.61,
         55.60, 47.78, 54.98, 50.39, 56.60, 54.96, 51.43, 51.81, 50.93, 59.43,
         55.73, 50.66, 52.80, 56.43, 57.30, 48.94, 51.25, 48.34, 47.45, 54.74,
         48.56, 52.38, 53.72, 50.55, 53.86])
al=0.025

  Ho will believe both are equal

ha will believe there is a difference in it

In [13]:
t_value=st.t.ppf(1-alpha,34)

In [14]:
T_calculation=(np.mean(data2)-np.mean(data1))/(np.sqrt((np.square(np.std(data2))/35)+((np.square(np.std(data1))/35))))

In [15]:
#By cuting the formula into two pieces
Cal1=(np.mean(data2)-np.mean(data1))
Cal1

np.float64(1.3908571428571364)

In [16]:
Cal2=(np.sqrt((np.square(np.std(data2))/35)+((np.square(np.std(data1))/35))))
Cal2

np.float64(0.9688179085574807)

In [17]:
Total_Cal=Cal1/Cal2
Total_Cal

np.float64(1.4356228663527184)

In [18]:
T_calculation

np.float64(1.4356228663527184)

In [19]:
if t_value<T_calculation:
    print("Ha is right")
else:
    print("Ho is right")

Ho is right


SO there is No difference in both of these Values

                                                         CHI SQUARE TEST

In [20]:
# 120 Rolls of Dice and we observed these values, And expect the others
# So have to check weather the dice is GOOD or not
Obs=np.array([22,17,20,26,22,13])
Exp=np.array([20,20,20,20,20,20])
Chi_table=11.09

In [28]:
Chi_cal=np.sum(np.square(Obs-Exp)/Exp)
Chi_cal

np.float64(5.1000000000000005)

Ho will believe that DICE IS FAIR

 Ha will believe that DICE is not FAIR

In [22]:
if Chi_table<Chi_cal:
    print("Ha is right")
else:
    print("Ho is right")

Ho is right


                                            CHI SQUARE TEST for checking the Association BETEEN TWO
                                            Have to check weather there is a Association between OBS data and EXP data or not
                                            So Ho will say there is no Association there
                                            Ha will say there is a Association

In [78]:
row1=np.array([40,45,25,10])
row2=np.array([35,30,20,30])
Obs1=np.array([40,45,25,10,35,30,20,30])
Obs1

array([40, 45, 25, 10, 35, 30, 20, 30])

In [79]:
chi_table=st.chi2.ppf(1-0.05,3)    # 3 is Degree of freedom(DF)...............find by n-1 usually.....but with two OBSevant arrays it was find by (number of column-1)(number of rows-1)
chi_table

np.float64(7.814727903251179)

Still have to find EXCPECTED VALUES first

In [80]:
sum_r1=np.sum(row1)
sum_r2=np.sum(row2)
sum_rows=np.array([sum_r1,sum_r2])
sum_rows


array([120, 115])

In [81]:
sum_col=row1+row2
sum_col

array([75, 75, 45, 40])

In [82]:
Exp1=[
]
for i in sum_rows:
    for j in sum_col:
        k=(i*j)/235
        Exp1=np.append(Exp1,k)

In [83]:
chi_cal=np.sum(np.square(Obs-Exp1)/Exp1)
chi_cal

np.float64(13.788747987117553)

In [84]:
if chi_table<chi_cal:
    print("Ha is right")
else:
    print("Ho is right")

Ha is right


There is a Association