In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from narwhals.selectors import string
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

# ONE ENCODER(Nominal)

In [142]:
from sklearn.preprocessing import OneHotEncoder
data=pd.read_csv("Students.csv")
Data=pd.read_csv("factory_worker_data.csv")
data

Name  Age  CGPA (out of 4.00)  Daily Study Hours  \
0       Zain Tariq   24                2.61                1.3   
1     Fatima Nawaz   21                3.07                2.4   
2     Ahmed Sheikh   22                2.65                5.9   
3     Zain Qureshi   24                3.66                4.9   
4    Fatima Sheikh   20                2.54                1.3   
..             ...  ...                 ...                ...   
495    Hamza Nawaz   23                2.85                1.1   
496    Usman Malik   18                2.58                6.7   
497    Fatima Rana   21                3.23                3.2   
498      Ali Javed   19                3.82                2.9   
499  Usman Qureshi   23                2.28                7.8   

    Sports Involvement  IQ Score  
0                  Yes       112  
1                   No       126  
2                   No        97  
3                  Yes       102  
4                   No        97  
..                 ...       ...  
495                 No        97  
496                Yes       126  
497                 No       121  
498                Yes       137  
499                 No       132  

[500 rows x 6 columns]

In [6]:
sp=pd.DataFrame(data['Sports Involvement'])

In [7]:
data['Age'].unique()

array([24, 21, 22, 20, 19, 23, 18])

In [8]:
df=OneHotEncoder(drop='first').fit_transform(sp).toarray()


In [9]:
SP=pd.DataFrame(df,columns=['Sports Involvement Yes'])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Name                500 non-null    object 
 1   Age                 500 non-null    int64  
 2   CGPA (out of 4.00)  500 non-null    float64
 3   Daily Study Hours   500 non-null    float64
 4   Sports Involvement  500 non-null    object 
 5   IQ Score            500 non-null    int64  
dtypes: float64(2), int64(2), object(2)
memory usage: 23.6+ KB


In [11]:
data["Sports Involvement Yes"]=SP

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Name                    500 non-null    object 
 1   Age                     500 non-null    int64  
 2   CGPA (out of 4.00)      500 non-null    float64
 3   Daily Study Hours       500 non-null    float64
 4   Sports Involvement      500 non-null    object 
 5   IQ Score                500 non-null    int64  
 6   Sports Involvement Yes  500 non-null    float64
dtypes: float64(3), int64(2), object(2)
memory usage: 27.5+ KB


In [13]:
data.drop(["Sports Involvement"],axis=1,inplace=True)

In [14]:
data

Name  Age  CGPA (out of 4.00)  Daily Study Hours  IQ Score  \
0       Zain Tariq   24                2.61                1.3       112   
1     Fatima Nawaz   21                3.07                2.4       126   
2     Ahmed Sheikh   22                2.65                5.9        97   
3     Zain Qureshi   24                3.66                4.9       102   
4    Fatima Sheikh   20                2.54                1.3        97   
..             ...  ...                 ...                ...       ...   
495    Hamza Nawaz   23                2.85                1.1        97   
496    Usman Malik   18                2.58                6.7       126   
497    Fatima Rana   21                3.23                3.2       121   
498      Ali Javed   19                3.82                2.9       137   
499  Usman Qureshi   23                2.28                7.8       132   

     Sports Involvement Yes  
0                       1.0  
1                       0.0  
2                       0.0  
3                       1.0  
4                       0.0  
..                      ...  
495                     0.0  
496                     1.0  
497                     0.0  
498                     1.0  
499                     0.0  

[500 rows x 6 columns]

# Label ENCODING(Ordinal Cateogary)

In [143]:
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
n_df=pd.DataFrame(lbl.fit_transform(data['Name']))
n_df

0
0    98
1    35
2     8
3    95
4    38
..   ..
495  44
496  83
497  37
498  12
499  85

[500 rows x 1 columns]

In [16]:
lbl.fit(data['Name'])

LabelEncoder()

In [17]:
labled=lbl.transform(data['Name'])

In [18]:
data['Name']=labled

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Name                    500 non-null    int64  
 1   Age                     500 non-null    int64  
 2   CGPA (out of 4.00)      500 non-null    float64
 3   Daily Study Hours       500 non-null    float64
 4   IQ Score                500 non-null    int64  
 5   Sports Involvement Yes  500 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 23.6 KB


# Ordinal Encoding(In which the variables are connected with each other)

In [22]:
# Ordinal Coding of Depatment of Employes data

In [23]:
from sklearn.preprocessing import OrdinalEncoder

In [172]:
Data['Department'].unique()
qr=[['QC', 'Assembly', 'Packaging', 'Logistics', 'Maintenance']]
qr

[['QC', 'Assembly', 'Packaging', 'Logistics', 'Maintenance']]

In [173]:
oe=OrdinalEncoder(categories=qr)
DF=pd.DataFrame(Data['Department'])

In [178]:
oe.fit(DF)

OrdinalEncoder(categories=[['QC', 'Assembly', 'Packaging', 'Logistics',
                            'Maintenance']])

In [179]:
oe.transform(DF)

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [3.],
       [2.],
       [1.],
       [3.],
       [3.],
       [4.],
       [1.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [3.],
       [4.],
       [2.],
       [4.],
       [3.],
       [4.],
       [0.],
       [3.],
       [4.],
       [4.],
       [4.],
       [3.],
       [2.],
       [4.],
       [4.],
       [4.],
       [0.],
       [4.],
       [4.],
       [0.],
       [3.],
       [2.],
       [4.],
       [3.],
       [4.],
       [1.],
       [1.],
       [1.],
       [3.],
       [3.],
       [4.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [4.],
       [0.],
       [4.],
       [2.],
       [3.],
       [3.],
       [3.],
       [4.],
       [2.],
       [4.],
       [2.],
       [3.],
       [4.],
       [1.],
       [3.],
       [0.],
       [2.],
       [4.],

In [180]:
Data['Department'] = oe.transform(DF)

In [181]:
Data

WorkerID  Age  Experience  Department   Sensor_1   Sensor_2   Sensor_3  \
0      W1000   41           4         0.0   7.237457  -5.345062        NaN   
1      W1001   27           4         0.0  -6.099276   4.944228   5.751492   
2      W1002   40          11         0.0  14.163983   7.419787  13.026986   
3      W1003   25           2         1.0  -8.144112   6.022785   1.759761   
4      W1004   34           7         1.0   9.499723   8.917607  12.294359   
..       ...  ...         ...         ...        ...        ...        ...   
995    W1995   24           4         1.0   9.587238   1.885114   4.269326   
996    W1996   43          21         0.0  29.973041  20.812611  25.566959   
997    W1997   59          37         0.0  44.074508  40.501634  46.594357   
998    W1998   33           7         1.0  10.258249  13.489234  11.741711   
999    W1999   31           4         1.0   0.873051   1.330631  -1.988315   

      Sensor_4   Sensor_5   Sensor_6   Sensor_7   Sensor_8  
0     6.385978  -3.187778   1.808027  -0.814783   1.703951  
1    10.058490  -2.290655  -4.390271  -2.941448  -1.209291  
2    14.914357   9.171912   4.244171   8.623844  17.667626  
3     6.124397  -7.962622   0.358290   3.785899   7.801595  
4     8.376217   7.684377        NaN   8.400410   6.543665  
..         ...        ...        ...        ...        ...  
995   6.033614   5.863820   9.540423   2.733291   5.067890  
996  23.453233  26.480754  11.741634  13.371076  15.017197  
997  44.397847  56.208826  34.056741  40.547397  53.592097  
998   9.666289   5.280387  10.796173   3.011345   3.485525  
999  -0.353334   5.622802   4.769798   1.153185   6.442104  

[1000 rows x 12 columns]

In [185]:
oe1=OrdinalEncoder()
W_df=pd.DataFrame(Data['WorkerID'])

In [186]:
oe1.fit(W_df)

OrdinalEncoder()

In [187]:
oe1.transform(W_df)

array([[  0.],
       [  1.],
       [  2.],
       [  3.],
       [  4.],
       [  5.],
       [  6.],
       [  7.],
       [  8.],
       [  9.],
       [ 10.],
       [ 11.],
       [ 12.],
       [ 13.],
       [ 14.],
       [ 15.],
       [ 16.],
       [ 17.],
       [ 18.],
       [ 19.],
       [ 20.],
       [ 21.],
       [ 22.],
       [ 23.],
       [ 24.],
       [ 25.],
       [ 26.],
       [ 27.],
       [ 28.],
       [ 29.],
       [ 30.],
       [ 31.],
       [ 32.],
       [ 33.],
       [ 34.],
       [ 35.],
       [ 36.],
       [ 37.],
       [ 38.],
       [ 39.],
       [ 40.],
       [ 41.],
       [ 42.],
       [ 43.],
       [ 44.],
       [ 45.],
       [ 46.],
       [ 47.],
       [ 48.],
       [ 49.],
       [ 50.],
       [ 51.],
       [ 52.],
       [ 53.],
       [ 54.],
       [ 55.],
       [ 56.],
       [ 57.],
       [ 58.],
       [ 59.],
       [ 60.],
       [ 61.],
       [ 62.],
       [ 63.],
       [ 64.],
       [ 65.],
       [ 6

In [189]:
Data['WorkerID']=oe1.transform(W_df)

In [190]:
Data

WorkerID  Age  Experience  Department   Sensor_1   Sensor_2   Sensor_3  \
0         0.0   41           4         0.0   7.237457  -5.345062        NaN   
1         1.0   27           4         0.0  -6.099276   4.944228   5.751492   
2         2.0   40          11         0.0  14.163983   7.419787  13.026986   
3         3.0   25           2         1.0  -8.144112   6.022785   1.759761   
4         4.0   34           7         1.0   9.499723   8.917607  12.294359   
..        ...  ...         ...         ...        ...        ...        ...   
995     995.0   24           4         1.0   9.587238   1.885114   4.269326   
996     996.0   43          21         0.0  29.973041  20.812611  25.566959   
997     997.0   59          37         0.0  44.074508  40.501634  46.594357   
998     998.0   33           7         1.0  10.258249  13.489234  11.741711   
999     999.0   31           4         1.0   0.873051   1.330631  -1.988315   

      Sensor_4   Sensor_5   Sensor_6   Sensor_7   Sensor_8  
0     6.385978  -3.187778   1.808027  -0.814783   1.703951  
1    10.058490  -2.290655  -4.390271  -2.941448  -1.209291  
2    14.914357   9.171912   4.244171   8.623844  17.667626  
3     6.124397  -7.962622   0.358290   3.785899   7.801595  
4     8.376217   7.684377        NaN   8.400410   6.543665  
..         ...        ...        ...        ...        ...  
995   6.033614   5.863820   9.540423   2.733291   5.067890  
996  23.453233  26.480754  11.741634  13.371076  15.017197  
997  44.397847  56.208826  34.056741  40.547397  53.592097  
998   9.666289   5.280387  10.796173   3.011345   3.485525  
999  -0.353334   5.622802   4.769798   1.153185   6.442104  

[1000 rows x 12 columns]

In [191]:
from sklearn.impute import SimpleImputer

In [195]:
si=SimpleImputer(strategy='mean')

In [211]:
F_value=SimpleImputer().fit_transform(Data[['Sensor_1', 'Sensor_2', 'Sensor_3','Sensor_4', 'Sensor_5', 'Sensor_6', 'Sensor_7', 'Sensor_8']])

In [212]:
Data.select_dtypes(include=[float]).columns

Index(['WorkerID', 'Department', 'Sensor_1', 'Sensor_2', 'Sensor_3',
       'Sensor_4', 'Sensor_5', 'Sensor_6', 'Sensor_7', 'Sensor_8'],
      dtype='object')

In [215]:
Data[['Sensor_1', 'Sensor_2', 'Sensor_3',
       'Sensor_4', 'Sensor_5', 'Sensor_6', 'Sensor_7', 'Sensor_8']]=F_value

In [218]:
Data
# Now this DATA is fully ready to work in Machine learning

WorkerID  Age  Experience  Department   Sensor_1   Sensor_2   Sensor_3  \
0         0.0   41           4         0.0   7.237457  -5.345062  11.273328   
1         1.0   27           4         0.0  -6.099276   4.944228   5.751492   
2         2.0   40          11         0.0  14.163983   7.419787  13.026986   
3         3.0   25           2         1.0  -8.144112   6.022785   1.759761   
4         4.0   34           7         1.0   9.499723   8.917607  12.294359   
..        ...  ...         ...         ...        ...        ...        ...   
995     995.0   24           4         1.0   9.587238   1.885114   4.269326   
996     996.0   43          21         0.0  29.973041  20.812611  25.566959   
997     997.0   59          37         0.0  44.074508  40.501634  46.594357   
998     998.0   33           7         1.0  10.258249  13.489234  11.741711   
999     999.0   31           4         1.0   0.873051   1.330631  -1.988315   

      Sensor_4   Sensor_5   Sensor_6   Sensor_7   Sensor_8  
0     6.385978  -3.187778   1.808027  -0.814783   1.703951  
1    10.058490  -2.290655  -4.390271  -2.941448  -1.209291  
2    14.914357   9.171912   4.244171   8.623844  17.667626  
3     6.124397  -7.962622   0.358290   3.785899   7.801595  
4     8.376217   7.684377   6.932269   8.400410   6.543665  
..         ...        ...        ...        ...        ...  
995   6.033614   5.863820   9.540423   2.733291   5.067890  
996  23.453233  26.480754  11.741634  13.371076  15.017197  
997  44.397847  56.208826  34.056741  40.547397  53.592097  
998   9.666289   5.280387  10.796173   3.011345   3.485525  
999  -0.353334   5.622802   4.769798   1.153185   6.442104  

[1000 rows x 12 columns]